---
apiVersion: v1
kind: ReplicationController
metadata:
  name: demoapp
  labels:
    app: demoapp
    version: "1.0"
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: demoapp
        version: "1.0"
    spec:
      containers:
        - name: demoapp-container
          image: registry.default.svc.appfactory.local:5000/demoapp 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: "http-server"
