---
kind: Service
apiVersion: v1
metadata:
  name: demoapp-prod
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: demoapp
    version: "1.0"
